#!/bin/sh
# Regenerate CLAUDE.md from AGENTS.md (single source of truth).
set -e

REPO_ROOT="$(git rev-parse --show-toplevel)"
AGENTS="$REPO_ROOT/AGENTS.md"
CLAUDE="$REPO_ROOT/CLAUDE.md"

if [ ! -f "$AGENTS" ]; then
  echo "AGENTS.md not found – nothing to sync." >&2
  exit 1
fi

{
  echo '<!-- AUTO-MIRRORED from AGENTS.md — do NOT edit this file; edit AGENTS.md instead. -->'
  echo ''
  cat "$AGENTS"
} > "$CLAUDE"

echo "CLAUDE.md synced from AGENTS.md."
